### ISSUE TITLE
v1.0.0.-rc1 - secvarctl sigsegv while reading fuzzed ESL file

### ISSUE THREAD

**Issue by nasastry** [open-power/secvarctl#63]
```
[root@ltcrain80-lp2 home]# secvarctl read -e PK.esl.sigsegv
	ESL SIG LIST SIZE: 857
	GUID is : a159c0a5e494a74a87b5ab155c2bf072
	Signature type is: X509
Segmentation fault (core dumped)
```

and with earlier secvarctl not seen the SIGSEGV - (probable git head at e3658f2ce5d0089e72eb243e8deacaa2ddd577a4)

```
[root@ltcrain80-lp2 home]# /home/secvarctl/secvarctl -m guest read -e PK.esl.sigsegv
	ESL SIG LIST SIZE: 857
	GUID is : a159c0a5e494a74a87b5ab155c2bf072
	Signature type is: X509
	Found 0 ESL's

RESULT: SUCCESS

```

**Comment by nasastry** [comment]
[PK.esl.sigsegv.txt](https://github.com/open-power/secvarctl/files/12790513/PK.esl.sigsegv.txt)

And the bt from core:
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fffae8b6390 in ASN1_get_object () from /lib64/libcrypto.so.3
Missing separate debuginfos, use: dnf debuginfo-install secvarctl-1.0.0-1.el9.ppc64le
(gdb) bt
#0  0x00007fffae8b6390 in ASN1_get_object () from /lib64/libcrypto.so.3
#1  0x00007fffae8cd780 in asn1_check_tlen.lto_priv () from /lib64/libcrypto.so.3
#2  0x00007fffae8d36b0 in asn1_item_embed_d2i () from /lib64/libcrypto.so.3
#3  0x00007fffae8d4444 in ASN1_item_d2i_ex () from /lib64/libcrypto.so.3
#4  0x00007fffae8d4520 in ASN1_item_d2i () from /lib64/libcrypto.so.3
#5  0x00007fffaeae0e38 in d2i_X509 () from /lib64/libcrypto.so.3
#6  0x000000010460aee8 in print_variables.constprop ()
#7  0x000000010460e804 in guest_read_command ()
#8  0x00000001045f3600 in main ()
```

**Comment by nasastry** [comment]
with RC2 not seeing this error
```
[root@ltcrain80-lp2 home]# secvarctl read -e PK.esl.sigsegv
ESL's internal sizes are not OK
Error reading from esl buffer: 2
RESULT: FAILURE

```
