### ISSUE TITLE
[bug][rc3][regression] read SIGSEGV while reading a valid certificate

### ISSUE THREAD

**Issue by nasastry** [open-power/secvarctl#78]
While reading a certificate using '-c' option seen SIGSEGV

/usr/bin/secvarctl read -c /home/secvarctl/test/guest/testdata/x509certs/grubdb_by_KEK.crt
Segmentation fault (core dumped)

from gdb:
Core was generated by `/usr/bin/secvarctl read -c /home/secvarctl/test/guest/testdata/x509certs/grubdb'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000000105f6f620 in guest_read_command ()
Missing separate debuginfos, use: dnf debuginfo-install secvarctl-1.0.0-1.el9.ppc64le
(gdb) bt
#0  0x0000000105f6f620 in guest_read_command ()
#1  0x0000000105f53620 in main ()

This issue not seen in RC2/RC1.

**Comment by nasastry** [comment]
[grubdb_by_KEK.crt.txt](https://github.com/open-power/secvarctl/files/13807194/grubdb_by_KEK.crt.txt)

**Comment by nasastry** [comment]
from dmesg:
```
[5770797.991240] secvarctl[470043]: segfault (11) at 0 nip 13748f620 lr 13748edf8 code 1 in secvarctl[137470000+30000]
[5770797.991265] secvarctl[470043]: code: 4bfffce8 60000000 60000000 60000000 7b690520 3c82fffe 2c290fc0 3884a278
[5770797.991271] secvarctl[470043]: code: 408003d8 78890520 2c290fc0 408003cc <7c20ded9> 7c0026d9 11a10507 419a045c
```

**Comment by nasastry** [comment]
Not seeing the raised error with the patch. Closing the issue.
```
[root@ltcrain80-lp2 secvarctl]# ./bin/secvarctl read -c grubdb_by_KEK.crt
	Found certificate info
 Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            6c:53:ee:19:4a:b4:3e:dc:be:46:00:9f:2f:ee:2d:3b:cb:ea:e1:b8
        Signature Algorithm: sha256WithRSAEncryption
        Issuer:
            countryName               = NC
            organizationName          = testing corp
        Validity
            Not Before: Apr  7 09:18:58 2023 GMT
            Not After : May  7 09:18:58 2023 GMT
        Subject:
            countryName               = NC
            organizationName          = testing corp
        X509v3 extensions:
            X509v3 Subject Key Identifier:
                6E:2D:F8:11:A6:F1:2E:70:D5:4D:C5:78:10:1F:C4:F5:97:6A:BA:C1
            X509v3 Authority Key Identifier:
                6E:2D:F8:11:A6:F1:2E:70:D5:4D:C5:78:10:1F:C4:F5:97:6A:BA:C1
            X509v3 Basic Constraints: critical
                CA:TRUE

RESULT: SUCCESS
```
